# Generated by Django 5.0.4 on 2024-05-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSnapSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=700)),
                ('redirect_uri', models.CharField(max_length=700)),
                ('account_id', models.CharField(max_length=700)),
            ],
            options={
                'verbose_name': 'UserSnapSetting',
                'verbose_name_plural': 'UserSnapSettings',
            },
        ),
    ]
